import "./App.css";
import { Input } from "./components/ui/input";
import { Button } from "./components/ui/button";

function App() {
	return (
		<div className="bg-muted min-h-screen p-5">
			<main className="w-xl mx-auto">
				<h1 className="text-2xl font-bold">Binary Search Visualizer</h1>
				<p className="text-muted-foreground text-sm">
					The BinaVry Search Visualizer is an interactive React application
					designed to help users understand and visualize the binary search
					algorithm. Users can input a list of comma-separated numbers and a
					target value, and the application automatically checks if the list is
					sorted, sorts it if necessary, and performs a binary search to find
					the target. The visualization highlights the current search range, the
					middle element being evaluated, and the final result (if found) with
					clear color-coded indicators. Each step of the algorithm is animated,
					making it easy to follow the process of narrowing down the search
					range. This tool is perfect for students, developers, and anyone
					looking to deepen their understanding of binary search in an engaging
					and intuitive way.
					<span className="italic font-bold">
						This text has been generated by AI.
					</span>
				</p>

				<div className="flex flex-col gap-4 items-start mt-6">
					<div className="w-full">
						<label>Numbers: </label>
						<Input placeholder="e.g., 1,2,3,4,5,6..." />
					</div>
					<div className="w-full">
						<label>Target: </label>
						<Input />
					</div>
					<Button className="cursor-pointer">Search</Button>
				</div>

				<div className="grid grid-cols-6 gap-2 mt-6">
					{Array.from(Array(10).keys()).map(() => (
						<div className="border bg-white rounded-lg flex flex-col justify-center items-center p-4">
							<span className="font-bold">10</span>
							<span className="text-muted-foreground text-sm">0</span>
						</div>
					))}
				</div>

				<div className="bg-white rounded-lg px-4 py-2 border mt-6">
					Index found!
				</div>
				<div className="flex flex-row gap-4">
					<div className="flex items-center gap-1">
						<div className="w-3 h-3 rounded-full bg-orange-500"></div>
						<span className="text-sm">Middle Element</span>
					</div>
					<div className="flex items-center gap-1">
						<div className="w-3 h-3 rounded-full bg-lime-500"></div>
						<span className="text-sm">Search range</span>
					</div>
					<div className="flex items-center gap-1">
						<div className="w-3 h-3 rounded-full bg-teal-500"></div>
						<span className="text-sm">Found Element</span>
					</div>
				</div>
			</main>
		</div>
	);
}

export default App;
